CREATE TABLE [ERP].[CuentaPaciente]
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	AtencionId INT NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFin DATE NOT NULL,
	RowVersion  TIMESTAMP  NOT NULL
	FOREIGN KEY (AtencionId) REFERENCES HIS.Atencion(Id),
)
